# Generated by Django 4.0.4 on 2022-05-18 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eraM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.CharField(default=' 年～', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='genreM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='WH', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='mainWordM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainword', models.CharField(default='noWord', max_length=20)),
                ('madeby', models.CharField(default='anonymous', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='記事')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('update_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainword_article', to='summer.mainwordm')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
            },
        ),
        migrations.CreateModel(
            name='AboutM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='要約')),
                ('textMore', models.TextField(verbose_name='common')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('update_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genre_about', to='summer.genrem')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='era_about', to='summer.eram')),
            ],
            options={
                'verbose_name': '要約2',
                'verbose_name_plural': '要約3',
            },
        ),
    ]
